/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_billing_system;

/**
 *
 * @author Saajan
 */

import javax.swing.*;
import java.sql.*;
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        initComponents();
        setTitle("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        radio_admin = new javax.swing.JRadioButton();
        radio_waiter = new javax.swing.JRadioButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 177, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        radio_admin.setText("Admin");
        getContentPane().add(radio_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        radio_waiter.setText("Waiter");
        radio_waiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_waiterActionPerformed(evt);
            }
        });
        getContentPane().add(radio_waiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 177, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 730, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to close Applcation?","Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a==0)
        {
            System.exit(0);
        } 
    }//GEN-LAST:event_exitActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
         try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           
           Connection con = DriverManager.getConnection
                   ("jdbc:mysql://localhost:3306/rbs","root","");
           if(radio_waiter.isSelected())
           {
                
               PreparedStatement ps= con.prepareStatement
             ("Select * from waiter where username=? AND password=? ");
             String username1 = username.getText();
            ps.setString(1,username.getText());
            ps.setString(2,password.getText());
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                    this.dispose();
                   Waiter_DashBoard sp = new Waiter_DashBoard(username1);
                   sp.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"wrong username or password");
           }
                
           }
           else if(radio_admin.isSelected())
           {
                 PreparedStatement ps= con.prepareStatement
             ("Select * from admin where username=? AND password=? ");
           
            ps.setString(1,username.getText());
            ps.setString(2,password.getText());
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                    this.dispose();
                    Admin_DashBoard ad = new Admin_DashBoard();
                    ad.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"wrong username or password");
                username.setText("");
                password.setText("");
           }
               
           }
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Incorrect username or password","Alert",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_loginActionPerformed

    private void radio_waiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_waiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_waiterActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton radio_admin;
    private javax.swing.JRadioButton radio_waiter;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
